version: '3.8'

services:
  php:
    build:
      context: docker
      dockerfile: php/Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/symfony
    ports:
      - "9000:9000"
    working_dir: /var/www/symfony

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8070:80"
    volumes:
      - ./src:/var/www/symfony
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php